redis:
  image: redis
  container_name: cache
  expose:
    - 6379
  ports:
    - 6379:6379
# monitor:
#   build: ./
#   volumes:
#     - ./:/var/www/app
#   links:
#     - redis
#   ports:
#     - 3001:3001
#   command: sh -c 'npm i && node queue-monitor.js'
restapi:
  build: ./restapi
  volumes:
    - ./restapi/:/var/www/app
  links:
    - redis
  ports:
    - 5000:5000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=5000
    - SOCKET=http://95.216.70.139:3000/fuzzers
  command: sh -c 'npm i && node index.js'
